name: community_islamic_app
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  velocity_x: ^4.2.1
  flutter_qiblah: ^3.0.3
  geocoding: ^3.0.0
  geolocator: ^11.1.0
  permission_handler: ^11.3.1
  intl: ^0.19.0
  http: ^1.2.2
  animated_notch_bottom_bar: ^1.0.3
  url_launcher: ^6.3.0
  flutter_local_notifications: ^17.2.1+2
  timezone: ^0.9.4
  audioplayers: ^6.0.0
  just_audio: ^0.9.39
  audio_service: ^0.18.15
  shared_preferences: ^2.3.1
  dio: ^5.5.0+1
  path_provider: ^2.1.4
  google_fonts: ^6.2.1
  rxdart: ^0.28.0
  flutter_polyline_points: ^2.1.0
  google_maps_flutter: ^2.9.0
  location: ^7.0.0
  flutter_svg: ^2.0.10+1
  firebase_core: ^3.3.0
  firebase_messaging: ^15.0.4
  app_settings: ^5.1.1
  firebase_database: ^11.0.4
  uuid: ^4.4.2
  firebase_analytics: ^11.2.1
  cloud_firestore: ^5.2.1
  photo_view: ^0.15.0
  image_picker: ^1.1.2
  connectivity_plus: ^6.0.5
  flutter_easyloading: ^3.0.5
  auto_scroll_text: ^0.0.7
  # alarm: ^3.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/home_icon/
    - assets/social_icon/
    - assets/splash_icon/
    - assets/images/

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: JameelNori1
      fonts:
        - asset: assets/fonts/jameelNori1.ttf
    - family: JameelNori2
      fonts:
        - asset: assets/fonts/jameelNori2.ttf
    - family: Poppins-Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: Poppins-SemiBold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
