// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9sWt9lcelENs_ExH5_e4BCbg9stPdpz4',
    appId: '1:19673110035:web:ae078235b432bdaf0d51e6',
    messagingSenderId: '19673110035',
    projectId: 'rosember-comunity-app-63216',
    authDomain: 'rosember-comunity-app-63216.firebaseapp.com',
    storageBucket: 'rosember-comunity-app-63216.appspot.com',
    measurementId: 'G-RSDS3X66L3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQONe2bJH2LkqjDYHNQaf2gA7a06InTX0',
    appId: '1:19673110035:android:24d15510be2b6f650d51e6',
    messagingSenderId: '19673110035',
    projectId: 'rosember-comunity-app-63216',
    storageBucket: 'rosember-comunity-app-63216.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARp2MytITu1JRJdMTu9YoB5nSmoxK_Gj4',
    appId: '1:19673110035:ios:f39fc85cf1b7e12c0d51e6',
    messagingSenderId: '19673110035',
    projectId: 'rosember-comunity-app-63216',
    storageBucket: 'rosember-comunity-app-63216.appspot.com',
    iosBundleId: 'com.example.communityIslamicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARp2MytITu1JRJdMTu9YoB5nSmoxK_Gj4',
    appId: '1:19673110035:ios:f39fc85cf1b7e12c0d51e6',
    messagingSenderId: '19673110035',
    projectId: 'rosember-comunity-app-63216',
    storageBucket: 'rosember-comunity-app-63216.appspot.com',
    iosBundleId: 'com.example.communityIslamicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9sWt9lcelENs_ExH5_e4BCbg9stPdpz4',
    appId: '1:19673110035:web:a42e143e3957fb4f0d51e6',
    messagingSenderId: '19673110035',
    projectId: 'rosember-comunity-app-63216',
    authDomain: 'rosember-comunity-app-63216.firebaseapp.com',
    storageBucket: 'rosember-comunity-app-63216.appspot.com',
    measurementId: 'G-JM2B1KEEBK',
  );
}
